name: e_commerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  go_router: ^14.3.0
  # di
  get_it: ^7.7.0
  # hive
  hive: ^2.2.3
  # rest api
  dio: ^5.4.3+1
  dio_retry_plus: ^2.0.7
  # path
  path_provider: ^2.1.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/db/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
